apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: project1    # Updated namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp-container
        image: http
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: http
  namespace: project1    # Updated namespace
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: webapp
